import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/admin-globals.css";
import { SidebarDemo } from "./pages/sidebardemo";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  RedirectToSignIn,
  UserButton,
} from "@clerk/nextjs";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider afterSignOutUrl="/admin">
          <main>
            <SignedOut>
              {/* Redirect to Clerk's sign-in page */}
              <RedirectToSignIn />
            </SignedOut>
            <SignedIn>
              <div className="flex h-screen">
                {/* Sidebar */}
                <aside className="w-64 bg-gray-800 text-white fixed h-full">
                  <SidebarDemo />
                </aside>

                {/* Main content area */}
                <div className="flex flex-col flex-grow ml-64">
                  <header className="p-4 bg-gray-100 border-b">
                    <UserButton showName />
                  </header>

                  <main className="flex-grow p-6 bg-white">{children}</main>
                </div>
              </div>
            </SignedIn>
          </main>
        </ClerkProvider>
      </body>
    </html>
  );
}
